version: '3.8'

services:
  web:
    image: arnabdaz/notespuker:1
    env_file:
      - ./config/config.env
    command: pm2-runtime start app.js
    depends_on:
      - mongo
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  mongo:
    image: mongo:7.0.5
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  nginx:
    image: arnabdaz/nginx-certbot:1
    environment:
      - CERTBOT_EMAIL=example@email.com
      - CERTBOT_DOMAINS=example.com
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    restart: unless-stopped

volumes:
  mongo-data:
  letsencrypt:

networks:
  default:
    driver: bridge
