version: '3.8'

services:
  web:
    build: .
    env_file:
      - ./config/config.env
    command: pm2-runtime start app.js
    depends_on:
      - mongo
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  mongo:
    image: mongo:7.0.5
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  nginx:
    image: nginx:1.24.0-alpine3.17
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  default:
    driver: bridge
